### PR TITLE
Rename artifact name ocjdbc -> jdbc.

### PR DESCRIPTION
**Pull request by songy23**

### CODE REVIEW

**Comment by odeke-em** [comment]
Thanks for this change @songy23! Unfortunately, I'd rather we stay away from having our package name be jdbc because that's a trademarked name and owned by Oracle whereas we are an open source project, I think ocjdbc sufficiently expresses our project without having to innocently get into legal :)

**Comment by songy23** [comment]
Chatted offline, we thought it's better to not use the Oracle trademarked name "jdbc" and keep "ocjdbc". Don't want to get into trouble with the "jdbc" name.

/cc @bogdandrutu

**Comment by bogdandrutu** [comment]
I don't think this is a problem.

**Comment by songy23** [comment]
A few other examples:
`com.microsoft.sqlserver.jdbc`: https://github.com/Microsoft/mssql-jdbc/tree/dev/src/main/java/com/microsoft/sqlserver/jdbc

`com.mongodb.jdbc`: https://github.com/erh/mongo-jdbc/tree/master/src/main/com/mongodb/jdbc

**Comment by odeke-em** [comment]
Interesting, to be honest I don't know much about Java naming and the ecosystem so I'll defer to the both of you @songy23 and @bogdandrutu, please feel free to make these changes.

**Pull request merged**
