### PR TITLE
Add Java style check and errorProne to Gradle.

### PR DESCRIPTION
**Pull request by songy23**
Fixes https://github.com/opencensus-integrations/ocjdbc/issues/21.

Also fixes Java style violations.

### CODE REVIEW

**Comment by songy23** [comment]
FYI do not review https://github.com/opencensus-integrations/ocjdbc/pull/27/commits/1b4d0375d5e6ce2e02bf00d9d2b25381ba16e583 - it's auto-generated by running the formatter (`$ ./gradlew goJF`).

**Comment by odeke-em** [comment]
Thanks for the PR @songy23! Am a little confused at the style check last commit, it seems like it just replaced the amount of spaces. Can we make sure that we don't artificially induce spurious changes? 2 spaces vs 4 space etc or tabs vs spaces isn't a direction I think we should be taking.

**Comment by songy23** [comment]
> Can we make sure that we don't artificially induce spurious changes? 2 spaces vs 4 space etc or tabs vs spaces isn't a direction I think we should be taking.

Unfortunately this is an official Java style requirement enforced by Google Java format. See http://google.github.io/styleguide/javaguide.html#s4.2-block-indentation for details.

In addition, all those changes were automatically generated by the formatter.

**Comment by songy23** [comment]
FYI running `$ ./gradlew goJF` is equivalent to running `$ go fmt`.

**Comment by odeke-em** [comment]
Ahh, I see. I am then going to have to adjust my code editor but if there was away to avoid such that'd be great!

**Comment by odeke-em** [comment]
So @songy23 just to clarify, only the build.gradle file is human written, the rest are just auto-generated right?

**Comment by bogdandrutu** [comment]
@odeke-em yes everything else gradlew and ./gradle dir are auto-generated.

**Pull request merged**
