### PR TITLE
all: prefix classes with OcWrap to declare intention

### LINKED ISSUE #19: all: make wrapper class names different from the interfaces they implement
In java is a bad practice to have implementation class have the same name as the interface that they implement because of how imports work in Java.

Consider to change all the class names to something more specific to OpenCensus.
https://github.com/opencensus-integrations/ocjdbc/blob/master/src/main/java/io/opencensus/integration/ocjdbc/CallableStatement.java

Maybe:
WrapCallableStatement
ObservabilityCallableStatement
or any other suggestion is fine.

### PR DESCRIPTION
**Pull request by odeke-em**
As recommended by team, prefix OcWrap in front of classes
to declare their intention rather than them sharing the
names of the java.sql classes that they wrap.

Fixes #19

### CODE REVIEW

**Comment by odeke-em** [comment]
>Maybe use OcWrap*? (To differentiate from other Wrap if there are any in users' application.)

Sure, let me make that update.

**Comment by odeke-em** [comment]
Alright, I've updated the class prefix with `OCWrap` PTAL.

**Comment by songy23** [comment]
Please use "OcWrap" (camel case) instead of "OCWrap". See Google Java format guide: http://google.github.io/styleguide/javaguide.html#s5.3-camel-case.

**Comment by odeke-em** [comment]
>Please use "OcWrap" (camel case) instead of "OCWrap". See Google Java format guide: 

TIL about the camel case recommendation for Java vs Go.

I've updated to the Java recommendation, PTAL.

**Comment by odeke-em** [comment]
Thank you for the review @songy23!

**Pull request merged**
